### ISSUE TITLE
Read only file system

### ISSUE THREAD

**Issue by afrovita** [helmiau/OpenWrt-Rpi#25]
Apa defaut install read only file system

**Comment by helmiau** [comment]
> Apa defaut install read only file system

engga om, sudah coba burn di sdcard yg lain?

**Comment by afrovita** [comment]
2x install gak bisa edit file apapun, selalu Read Only File system,
release 21-8-21 rpi3
udah coba remount RW tetep readonly fie system
xderm jalan libernet ikut jalan sendiri

**Comment by helmiau** [comment]
bisa lihat log read only nya gimana?
device apa?

xderm & libernet sudah fix di update terakhir

**Comment by afrovita** [comment]
udah saya pasang yang releease terbaru dan normal
