### ISSUE TITLE
 Realtek PCI network card not detected because there's no driver

### ISSUE THREAD

**Issue by umarizulkifli** [helmiau/OpenWrt-Rpi#65]
**Bug Information**
Realtek PCI network card not detected because there's no driver.

**Device and OS Information:**
 - Device: ( give x between this sign [ ] )
     - [ ] Raspberry Pi
     - [ ] Nano Pi
     - [ ] Orange Pi
     - [ ] Amlogic s9xxx
     - [x] x86

 - Downloaded Firmware Name: ( see: **Supported Devices and Download Section** at my blog post )
         helmiwrt-21.02-x86-generic-generic-squashfs-combined.img.gz 

 - Device Model: ( see: **LuCI - Status - Overview - Model** )
       Netbook Lenovo S10-3

 - Firmware Build Version ( see: **LuCI - Status - Overview - Firmware Version** )
       HelmiWrt OS 2022.08.11

**Additional context**

Need kmod-r8101 

**Error Logs**
```
$ lspci -v
Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller [10ec:8136] (rev 02)
$ ifconfig eth0
ifconfig: eth0: error fetching interface information: Device not found
```

**Comment by helmiau** [comment]
are you tried to install driver manually @umarizulkifli ?

**Comment by umarizulkifli** [comment]
Yes
I'm trying to build https://github.com/umarizulkifli/immortalwrt/tree/openwrt-21.02/package/kernel/r8101

Submit a PR https://github.com/immortalwrt/immortalwrt/pull/760
