### ISSUE TITLE
Need driver for x86

### ISSUE THREAD

**Issue by umarizulkifli** [helmiau/OpenWrt-Rpi#66]
**Bug Information**
Need these drivers for x86

CONFIG_PACKAGE_kmod-r8101=y
CONFIG_PACKAGE_kmod-r8169=y
CONFIG_PACKAGE_r8169-firmware=y
CONFIG_PACKAGE_kmod-i2c-i801=y
CONFIG_PACKAGE_kmod-ath9k=y

**Device and OS Information:**
 - Device: ( give x between this sign [ ] )
     - [ ] Raspberry Pi
     - [ ] Nano Pi
     - [ ] Orange Pi
     - [ ] Amlogic s9xxx
     - [x] x86

 - Downloaded Firmware Name: ( see: **Supported Devices and Download Section** at my blog post )
       x86-generic squashfs UEFI ( this is an example, replace this line with your own )
       Raspberry Pi 4 squashfs factory ( this is an example, replace this line with your own )

 - Device Model: ( see: **LuCI - Status - Overview - Model** )
       Raspberry Pi 4 Model B Rev 1.2 ( this is an example, replace this line with your own )

 - Firmware Build Version ( see: **LuCI - Status - Overview - Firmware Version** )
       HelmiWrt R22.2.2 2022-02-18  ( this is an example, replace this line with your own )

**Additional context**
Add any other context about the problem here, such your advice or something else.

**Error Logs**
```
Write error logs here (replace this line)
Write error logs here (replace this line)
Write error logs here (replace this line)
```

**Comment by helmiau** [comment]
install it manually through opkg update
